server:
  port: 8082

spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # ?????Nacos?????
        username: nacos # ?????Nacos???
        password: nacos # ?????Nacos??

feign:
  hystrix:
    enabled: false