server:
  port: 8081
spring:
  application:
    name: surname-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: true

tianapi:
  key:
  url: https://apis.tianapi.com/surname/index
