wxy:
  username: "wxy"
  job: "666"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/share?useSSL=false&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver